### ISSUE TITLE
Exporting Preprocessed Corpus for application in R stm package

### ISSUE THREAD

**Issue by Farcyy** [WZBSocialScienceCenter/tmtoolkit#29]
First of all: Thank you so much for your amazing work! My research team is currently working on comparing the results of different topic-modelling approaches on a given text corpus. 

To strenghten comparability, we want to use a preprocessed text corpus from tmtoolkit, to use it in R stm package. Now the question: Is it possible to export tmtoolkit text corpuses with other formats than PICKLE (e.g. csv, txt) to use it in other packages? And have you worked on / heard of any comparable applications and their respective solutions?

Thank you so much for your help!

Best wishes,
Cons

**Comment by internaut** [comment]
Hi Cons,

this is something I have on my todo-list, but I rarely find the time to work on tmtoolkit at the moment.

Anyway, I think you can still quite easily achieve exporting the data from Python and importing it to R: I assume you only want to compare different Bag-of-Words based topic models. This means, you generally only need the document-term-matrix (DTM) data plus its "meta data", i.e. the document labels and the vocabulary.

A straight forward approach would be to use [dtm_to_dataframe](https://tmtoolkit.readthedocs.io/en/latest/api.html#tmtoolkit.bow.dtm.dtm_to_dataframe) to convert these three items to a single pandas dataframe that has the doc. labels in the rows, the vocab in the columns and the frequencies in the cells. You can then use this dataframe to [export to CSV](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html) and import the CSV into R.

This approach can be problematic when you have a very big DTM, since it converts the internally used sparse representation to a dense representation in pandas which uses much more RAM. So if you get out-of-memory errors, you will have to somehow export the sparse DTM and import it into R. Unfortunately, I've never done that so you'll have to dig into that yourself.

Good luck!
